# Generated by Django 4.0.4 on 2022-04-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newletter',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
