# Generated by Django 4.0.4 on 2022-04-28 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newletter_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
    ]
