# Generated by Django 4.0.4 on 2022-04-28 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_subscription_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='completed',
            new_name='confirm',
        ),
    ]
