# Generated by Django 4.0.4 on 2022-04-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('community manager', 'community manager'), ('accountant', 'accountant'), ('IT support', 'IT support'), ('CEO', 'CEO'), ('user', 'user')], default='user', max_length=255),
        ),
    ]
